export { default as ChooseLogins } from "./ChooseLogins";
export { default as RegisterGestUser } from "./RegisterGestUser";
export { default as RegisterMaintenanceCenterUser } from "./RegisterMaintenanceCenterUser";
export { default as LoginMaintenanceCenterUser } from "./LoginMaintenanceCenterUser";
export { default as LoginGestUser } from "./LoginGestUser";
export { default as ForgotPasswordGestUser } from "./ForgotPasswordGestUser";
export { default as ForgotPasswordMaintenanceCenter } from "./ForgotPasswordMaintenanceCenter";
export { default as ServiceRequest } from "./ServiceRequest";
export { default as ClientInterface } from "./ClientInterface";
export { default as ConfirmServiceRequest } from "./ConfirmServiceRequest";
export { default as RequestSuccess } from "./RequestSuccess";
export { default as CarTypesComponent } from "./CarTypesComponent";
export { default as LocationPicker } from "./LocationPicker";
export { default as Navbar } from "./Navbar";
export { default as Footer } from './Footer';
export { default as HeroSection } from "./HeroSection";
export { default as ProtectedRoute } from "./ProtectedRoute";
export { default as LandingPage } from "./LandingPage";
export { default as LoginAdmin } from "./LoginAdmin";
export { default as RegisterAdmin } from "./RegisterAdmin";
export { default as MaintenanceCentersAdmin } from "./MaintenanceCentersAdmin";
export { default as ListCustomersAdmin } from "./ListCustomersAdmin";
export { default as OrderListAdmin } from "./OrderListAdmin";
export { default as SettingsAdmin } from "./SettingsAdmin";
export { default as SideBarCenter } from "./SideBarCenter";

export { default as SideBar } from "./SideBar";
export { default as TopBar } from "./TopBar";
export { default as RequestProcessing } from "./RequestProcessing";
export { default as ListMaintenanceRequests } from "./ListMaintenanceRequests";
export { default as SettingsMaintenance } from "./SettingsMaintenance";
export { default as ProfileAdmin } from "./ProfileAdmin";
export { default as ProfileMaintenance } from "./ProfileMaintenance";
export { default as ContactUS } from "./ContactUS";
export { default as ProfileCustomer } from "./ProfileCustomer";
export { default as ReportAdmin } from "./ReportAdmin";
export * from "./design";

